=== Maulyanda/XML-XSD_WebService1154008/Mahasiswa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="dataproyek">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="mahasiswa"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="mahasiswa">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="npm"/>
                <xs:element ref="jurusan"/>
                <xs:element ref="nama"/>
                <xs:element ref="email"/>
                <xs:element ref="umur"/>
                <xs:element ref="jk"/>
                <xs:element ref="alamat"/>
                <xs:element ref="nomor_hp"/>
                <xs:element ref="hasil_proyek"/>
                <xs:element ref="pembimbing"/>
            </xs:sequence>
            <xs:attribute name="aktif_proyek" use="required" type="xs:NCName"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="npm" type="xs:integer"/>
    <xs:element name="jurusan" type="xs:string"/>
    <xs:element name="email">
    	<xs:simpleType>
    		<xs:restriction base="xs:string">

    			<xs:pattern value=".+@gmail.com"></xs:pattern>
    			<xs:minLength value="5"></xs:minLength>

    		</xs:restriction>
    	</xs:simpleType>
    </xs:element>
    <xs:element name="umur" type="xs:integer"/>
    <xs:element name="jk" type="xs:NCName"/>
    <xs:element name="alamat" type="xs:NCName"/>
    <xs:element name="nomor_hp" type="xs:integer"/>
    <xs:element name="hasil_proyek" type="xs:NCName"/>
    <xs:element name="pembimbing">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nik"/>
                <xs:element ref="nama"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="nik" type="xs:NMTOKEN"/>
    <xs:element name="nama" type="xs:string"/>
</xs:schema>

=== Maulyanda/XML-XSD_WebService1154008/Mahasiswa.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataproyek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Mahasiswa.xsd">
	<mahasiswa aktif_proyek ="ya">
		<npm>1154051</npm>
		<jurusan>Teknik Informatika</jurusan>
		<nama>Indra Riksa H.</nama>
		<email>indrariksa@gmail.com</email>
		<umur>19</umur>
		<jk>laki-laki</jk>
		<alamat>Cibiru</alamat>
		<nomor_hp>082267879675</nomor_hp>
		<hasil_proyek>A</hasil_proyek>
		<pembimbing>
			<nik>113.80.159</nik>
			<nama>M. Nurkamal Fauzan</nama>
		</pembimbing>
	</mahasiswa>	

	<mahasiswa aktif_proyek ="ya">
		<npm>1154061</npm>
		<jurusan>Teknik Informatika</jurusan>
		<nama>Berlin Mitra P.</nama>
		<email>berlinmitraa@gmail.com</email>
		<umur>19</umur>
		<jk>laki-laki</jk>
		<alamat>Cijirokaso</alamat>
		<nomor_hp>089877564312</nomor_hp>
		<hasil_proyek>B</hasil_proyek>
		<pembimbing>
			<nik>215.89.158</nik>
			<nama>Nisa Hanum Harani</nama>
		</pembimbing>	
	</mahasiswa>

	<mahasiswa aktif_proyek ="ya">
		<npm>1154009</npm>
		<jurusan>Teknik Informatika</jurusan>
		<nama>Agien Farhan S.</nama>
		<email>agienfarhan@gmail.com</email>
		<umur>19</umur>
		<jk>laki-laki</jk>
		<alamat>Cijirokaso</alamat>
		<nomor_hp>081389778567</nomor_hp>
		<hasil_proyek>B</hasil_proyek>
		<pembimbing>
			<nik>215.89.158</nik>
			<nama>Nisa Hanum Harani</nama>
		</pembimbing>
	</mahasiswa>	

	<mahasiswa aktif_proyek ="tidak">
		<npm>1154054</npm>
		<jurusan>Teknik Informatika</jurusan>
		<nama>Indra Saryoni S.</nama>
		<email>indrasaryoni@gmail.com</email>
		<umur>20</umur>
		<jk>laki-laki</jk>
		<alamat>Cijirokaso</alamat>
		<nomor_hp>082356876901</nomor_hp>
		<hasil_proyek>E</hasil_proyek>
		<pembimbing>
			<nik>115.88.193</nik>
			<nama>Roni Andarsyah</nama>
		</pembimbing>
	</mahasiswa>

	<mahasiswa aktif_proyek ="ya">
		<npm>1154021</npm>
		<jurusan>Teknik Informatika</jurusan>
		<nama>Kindi Herdiansyah</nama>
		<email>kindiherdi@gmail.com</email>
		<umur>19</umur>
		<jk>laki-laki</jk>
		<alamat>Cijirokaso</alamat>
		<nomor_hp>082278996545</nomor_hp>
		<hasil_proyek>B</hasil_proyek>
		<pembimbing>
			<nik>115.88.193</nik>
			<nama>Roni Andarsyah</nama>
		</pembimbing>			
	</mahasiswa>
	
	<mahasiswa aktif_proyek ="tidak">
		<npm>1154011</npm>
		<jurusan>Teknik Informatika</jurusan>
		<nama>Oka Irvian S.</nama>
		<email>okairvian@gmail.com</email>
		<umur>20</umur>
		<jk>laki-laki</jk>
		<alamat>Cijirokaso</alamat>
		<nomor_hp>082166987854</nomor_hp>
		<hasil_proyek>E</hasil_proyek>
		<pembimbing>
			<nik>215.86.148</nik>
			<nama>Rolly Maulana Awangga</nama>
		</pembimbing>
	</mahasiswa>
</dataproyek>
